apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: overlayimage2
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/dougtidwell/imageoverlay:v1
